@echo off
cd /d "C:\Users\Administrator\Downloads\Projects\designcalatlog\DesignElectronicsLabCatalog"
set VITE_SUPABASE_URL=https://xmymhkmmukxrffzkuxnd.supabase.co
set VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteW1oa21tdWt4cmZmemt1eG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1Nzk3OTUsImV4cCI6MjA5OTE1NTc5NX0.NqhNCwC1eO-O1B2Zu9CGFL3sZPrUfBSVI9gKf4-rg7w
npx vite --host 0.0.0.0